name: HACS Action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run HACS Action
        uses: hacs/action@v2
        with:
          category: integration
