name: Hassfest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Hassfest
        uses: home-assistant/actions/hassfest@v2
